services:
  postgres:
    image: postgres:latest
    container_name: blog-db
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: blog
    ports:
      - "5432:5432"